export const signup = async (req, res) => {
  try {
  } catch (error) {
    console.log(error.message);
    res.status(500).json({ error: error.message });
  }
};

export const login = async (req, res) => {
  try {
  } catch (error) {
    console.log(error.message);
    res.status(500).json({ error: error.message });
  }
};

export const logout = async (req, res) => {
  try {
  } catch (error) {
    console.log(error.message);
    res.status(500).json({ error: error.message });
  }
};
